variables:
  ADDRESS_PROD: harbor.emehmon.uz
  REPO_NAME: e-mehmon
  IMAGE_NAME: superadmin-front
  SERVICE_NAME: superadmin-front_superadmin-front
  SSH_TARGET: "master1"
  BRANCH: ${CI_COMMIT_REF_NAME}


stages:
  - build
  - push
  - deploy

build-job:
  stage: build
  only:
    - dev
    #- merge_requests
  tags:
    - stage-server
  script:
    - cd /home/emehmon_superadmin_front
    - pwd
    - whoami
    - git checkout dev
    - git reset --hard origin/dev
    - git pull origin dev
    - npm install
    - npm run build

#Production
build-prod:
  stage: build
  only:
    - prod
  tags:
    - e_mehmon_prod
  script:
    - pwd
    - whoami
    - git checkout prod || fail 
    - git reset --hard origin/prod || fail
    - git pull origin prod || fail
    - docker build --build-arg BRANCH=$BRANCH --build-arg VAULT_TOKEN=$PROD_VAULT_TOKEN -t $ADDRESS_PROD/$REPO_NAME/$IMAGE_NAME:${CI_PIPELINE_IID} .
# Push stage
push-harbor:
  stage: push
  only:
    - prod
  tags:
    - e_mehmon_prod
  script:
    - pwd
    - echo $HARBOR_PASSWORD_PROD | docker login -u harbor_prod --password-stdin $ADDRESS_PROD
    - docker push $ADDRESS_PROD/$REPO_NAME/$IMAGE_NAME:${CI_PIPELINE_IID}
    #- docker builder prune -af
    - docker image prune -af

#deploy
deploy-prod:
  stage: deploy
  only:
    - prod
  tags:
    - e_mehmon_prod
  script:
    - pwd
    - ssh "$SSH_TARGET" docker service update --update-order start-first --update-parallelism 1 --update-delay 10s --image "$ADDRESS_PROD/$REPO_NAME/$IMAGE_NAME:${CI_PIPELINE_IID}" "$SERVICE_NAME"
  retry: 2 
  timeout: 15m



